# Generated by Django 4.2.20 on 2025-10-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('OGOLNE', 'Ogólne'), ('TECHNICZNE', 'Techniczne pytania'), ('PORADY', 'Porady mechaniczne'), ('RECENZJE', 'Recenzje samochodów'), ('TUNING', 'Tuning'), ('ELEKTRO', 'Elektromobilność'), ('HISTORIA', 'Motoryzacja historyczna')], default='OGOLNE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('production_start', models.PositiveIntegerField(blank=True, null=True)),
                ('production_end', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Generacja',
                'verbose_name_plural': 'Generacje',
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car_history.vehiclemake')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='service_center',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pojazd', 'verbose_name_plural': 'Pojazdy'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Biały', 'Biały'), ('Srebrny', 'Srebrny'), ('Szary', 'Szary'), ('Czerwony', 'Czerwony'), ('Niebieski', 'Niebieski'), ('Zielony', 'Zielony'), ('Beżowy', 'Beżowy'), ('Żółty', 'Żółty'), ('Inny', 'Inny')], default='Biały', verbose_name='Kolor nadwozia'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registration',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data pierwszej rejestracji'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='Na sprzedaż'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/%Y/%m/%d/', verbose_name='Zdjęcie'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Beżowy', 'Beżowy'), ('Szary', 'Szary'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Inny', 'Inny')], default='Czarny', verbose_name='Kolor wnętrza'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cena (PLN)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheel_size',
            field=models.CharField(choices=[('15"', '15"'), ('16"', '16"'), ('17"', '17"'), ('18"', '18"'), ('19"', '19"'), ('20"', '20"'), ('21"', '21"'), ('22"', '22"')], default='', max_length=10, verbose_name='Rozmiar felg'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometer',
            field=models.PositiveIntegerField(verbose_name='Przebieg (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True, verbose_name='VIN'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ServiceCenter',
        ),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
        migrations.AddField(
            model_name='vehiclegeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='car_history.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car_history.discussion'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='car_history.vehiclegeneration'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclegeneration',
            unique_together={('model', 'name')},
        ),
    ]
