# Generated by Django 4.2.20 on 2025-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('Hybryda', 'Hybryda'), ('Elektryczny', 'Elektryczny'), ('Benzyna+LPG', 'Benzyna+LPG'), ('Benzyna+CNG', 'Benzyna+CNG')], default='', max_length=20, verbose_name='Typ paliwa'),
        ),
    ]
