# Generated by Django 4.2.20 on 2025-05-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
