# Generated by Django 4.2.20 on 2025-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0002_comment_discussion_vehiclegeneration_vehiclemake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='production_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rok produkcji'),
        ),
    ]
