# Generated by Django 4.2.20 on 2025-10-26 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0002_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sevice_entries', to='car_history.vehicle'),
        ),
    ]
