# Generated by Django 4.2.20 on 2025-10-14 20:59

import car_history.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0003_vehicle_production_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=car_history.utils.vehicle_image_path, verbose_name='Zdjęcie')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_history.vehicle', verbose_name='Pojazd')),
            ],
            options={
                'verbose_name': 'Zdjęcie pojazdu',
                'verbose_name_plural': 'Zdjęcia pojazdów',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
