# Generated by Django 4.2.20 on 2025-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0004_remove_vehicle_image_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(default='', verbose_name='Nr rejestracyjny'),
        ),
    ]
