# Generated by Django 4.2.20 on 2025-11-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0005_vehiclesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageentry',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_entries', to='car_history.vehicle'),
        ),
    ]
