# Generated by Django 4.2.20 on 2025-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0005_comment_discussion_delete_post_comment_discussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.CharField(choices=[('OGOLNE', 'Ogólne'), ('TECHNICZNE', 'Techniczne pytania'), ('PORADY', 'Porady mechaniczne'), ('RECENZJE', 'Recenzje samochodów'), ('TUNING', 'Tuning'), ('ELEKTRO', 'Elektromobilność'), ('HISTORIA', 'Motoryzacja historyczna')], default='OGOLNE', max_length=20),
        ),
        migrations.AddField(
            model_name='discussion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
