# Generated by Django 4.2.20 on 2025-11-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0006_alter_damageentry_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSaleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('favorites', models.PositiveIntegerField(default=0)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='car_history.vehiclesale')),
            ],
        ),
    ]
