# Generated by Django 4.2.20 on 2025-11-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0007_vehiclesalestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='car_history.vehiclesale'),
        ),
    ]
