# Generated by Django 4.2.20 on 2025-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0008_message_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='wheel_size',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(choices=[('FWD', 'Przedni (FWD)'), ('RWD', 'Tylny (RWD)'), ('AWD', 'Na wszystkie koła (AWD)'), ('4x4', '4x4')], default='FWD', max_length=10, verbose_name='Rodzaj napędu'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('Manualna', 'Manualna'), ('Automatyczna', 'Automatyczna'), ('Półautomatyczna', 'Półautomatyczna'), ('CVT', 'CVT (bezstopniowa)'), ('Dwusprzęgłowa', 'Dwusprzęgłowa (DSG/DCT)')], default='Manualna', max_length=20, verbose_name='Skrzynia biegów'),
        ),
    ]
