# Generated by Django 4.2.20 on 2025-10-07 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0008_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Biały', 'Biały'), ('Srebrny', 'Srebrny'), ('Szary', 'Szary'), ('Czerwony', 'Czerwony'), ('Niebieski', 'Niebieski'), ('Zielony', 'Zielony'), ('Beżowy', 'Beżowy'), ('Żółty', 'Żółty'), ('Inny', 'Inny')], default='Biały'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(choices=[('FWD', 'Napęd na przód'), ('RWD', 'Napęd na tył'), ('AWD', 'Napęd na wszystkie koła'), ('4WD', '4x4 / 4WD')], default='Napęd na przód', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registration',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('Hybryda', 'Hybryda'), ('Elektryczny', 'Elektryczny')], default='Diesel', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(choices=[('Czarny', 'Czarny'), ('Beżowy', 'Beżowy'), ('Szary', 'Szary'), ('Brązowy', 'Brązowy'), ('Biały', 'Biały'), ('Czerwony', 'Czerwony'), ('Inny', 'Inny')], default='Czarny'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_size',
            field=models.CharField(choices=[('195/65 R15', '195/65 R15'), ('205/55 R16', '205/55 R16'), ('225/45 R17', '225/45 R17'), ('235/40 R18', '235/40 R18'), ('245/35 R19', '245/35 R19'), ('255/30 R20', '255/30 R20'), ('265/35 R21', '265/35 R21'), ('275/30 R22', '275/30 R22')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automat', 'Automat')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheel_size',
            field=models.CharField(choices=[('15"', '15"'), ('16"', '16"'), ('17"', '17"'), ('18"', '18"'), ('19"', '19"'), ('20"', '20"'), ('21"', '21"'), ('22"', '22"')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True),
        ),
    ]
