# Generated by Django 4.2.20 on 2025-11-04 19:47

import car_history.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0009_remove_vehicle_wheel_size_vehicle_drive_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=car_history.utils.default_avatar_path, null=True, upload_to=car_history.utils.user_avatar_path, verbose_name='Zdjęcie profilowe'),
        ),
    ]
