# Generated by Django 4.2.20 on 2025-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0010_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='history_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf_exports/'),
        ),
    ]
