# Generated by Django 4.2.20 on 2025-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0013_commentstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
