# Generated by Django 4.2.20 on 2025-11-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0014_comment_dislikes_count_comment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
