# Generated by Django 4.2.20 on 2025-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0016_discussion_dislikes_count_discussion_favorites_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceentry',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
