# Generated by Django 4.2.20 on 2025-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0017_alter_serviceentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageentry',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
