# Generated by Django 4.2.20 on 2025-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0018_alter_damageentry_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageentry',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceentry',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
