# Generated by Django 4.2.20 on 2025-11-15 16:43

import car_history.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0019_alter_damageentry_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageentry',
            name='photos',
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=car_history.utils.damage_image_path)),
                ('damage_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='car_history.damageentry')),
            ],
        ),
    ]
