# Generated by Django 4.2.20 on 2025-11-25 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0020_remove_damageentry_photos_damagephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='first_registration',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Data pierwszej rejestracji'),
        ),
    ]
