# Generated by Django 4.2.20 on 2025-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0021_alter_vehicle_first_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_length',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
