# Generated by Django 4.2.20 on 2025-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0022_comment_content_length_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='images_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
