# Generated by Django 4.2.20 on 2025-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_history', '0024_alter_comment_discussion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', '-created_at'], name='car_history_discuss_e47345_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', '-likes_count'], name='car_history_discuss_c03471_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', '-content_length'], name='car_history_discuss_4d070e_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='car_history_author__3945d6_idx'),
        ),
    ]
